package projet.interfaces;
import java.awt.Container;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JButton;

public class Echiquier extends javax.swing.JFrame {

    /**
     * Creates new form Echiquier
     */
    public Echiquier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel0 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5  = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabelFond = new javax.swing.JLabel();

        
        setPreferredSize(new java.awt.Dimension(800, 610));
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(512, 512));
        jPanel1.setLayout(new java.awt.GridLayout(8, 8));

        jLabel0.setIcon(new javax.swing.ImageIcon(("TourNoir.png"))); // NOI18N
        jLabel0.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel0);

        jLabel1.setIcon(new javax.swing.ImageIcon(("CavalierNoir.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(("FouNoir.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel2);

        jLabel3.setIcon(new javax.swing.ImageIcon(("ReineNoir.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel3);

        jLabel4.setIcon(new javax.swing.ImageIcon(("RoiNoir.png"))); // NOI18N
        jPanel1.add(jLabel4);

        jLabel5.setIcon(new javax.swing.ImageIcon(("FouNoir.png"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel5);

        jLabel6.setIcon(new javax.swing.ImageIcon(("CavalierNoir.png"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel6);

        jLabel7.setIcon(new javax.swing.ImageIcon(("TourNoir.png"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel7);

        jLabel8.setIcon(new javax.swing.ImageIcon(("PionNoir.png"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel8);

        jLabel9.setIcon(new javax.swing.ImageIcon(("PionNoir.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel9);

        jLabel10.setIcon(new javax.swing.ImageIcon(("PionNoir.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel10);

        jLabel11.setIcon(new javax.swing.ImageIcon(("PionNoir.png"))); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel11);

        jLabel12.setIcon(new javax.swing.ImageIcon(("PionNoir.png"))); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel12);

        jLabel13.setIcon(new javax.swing.ImageIcon(("PionNoir.png"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel13);

        jLabel14.setIcon(new javax.swing.ImageIcon(("PionNoir.png"))); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel14);

        jLabel15.setIcon(new javax.swing.ImageIcon(("PionNoir.png"))); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel15);

        jLabel16.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel16);

        jLabel17.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel17);

        jLabel18.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel18);

        jLabel19.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel19);

        jLabel20.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel20);

        jLabel21.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel21);

        jLabel22.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel22);

        jLabel23.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel23);

        jLabel24.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel24);

        jLabel25.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel25);

        jLabel26.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel26);

        jLabel27.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel27);

        jLabel28.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel28);

        jLabel29.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel29);

        jLabel30.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel30);

        jLabel31.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel31);

        jLabel32.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel32);

        jLabel33.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel33);

        jLabel34.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel34);

        jLabel35.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel35);

        jLabel36.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel36);

        jLabel37.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel37);

        jLabel38.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel38);

        jLabel39.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel39);

        jLabel40.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel40);

        jLabel41.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel41);

        jLabel42.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel42);

        jLabel43.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel43);

        jLabel44.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel44);

        jLabel45.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel45);

        jLabel46.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel46);

        jLabel47.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel47);

        jLabel48.setIcon(new javax.swing.ImageIcon(("PionJaune.png"))); // NOI18N
        jLabel48.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel48);

        jLabel49.setIcon(new javax.swing.ImageIcon(("PionJaune.png"))); // NOI18N
        jLabel49.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(jLabel49);

        jLabel50.setIcon(new javax.swing.ImageIcon(("PionJaune.png"))); // NOI18N
        jPanel1.add(jLabel50);

        jLabel51.setIcon(new javax.swing.ImageIcon(("PionJaune.png"))); // NOI18N
        jPanel1.add(jLabel51);

        jLabel52.setIcon(new javax.swing.ImageIcon(("PionJaune.png"))); // NOI18N
        jPanel1.add(jLabel52);

        jLabel53.setIcon(new javax.swing.ImageIcon(("PionJaune.png"))); // NOI18N
        jPanel1.add(jLabel53);

        jLabel54.setIcon(new javax.swing.ImageIcon(("PionJaune.png"))); // NOI18N
        jPanel1.add(jLabel54);

        jLabel55.setIcon(new javax.swing.ImageIcon(("PionJaune.png"))); // NOI18N
        jPanel1.add(jLabel55);

        jLabel56.setIcon(new javax.swing.ImageIcon(("TourJaune.png"))); // NOI18N
        jPanel1.add(jLabel56);

        jLabel57.setIcon(new javax.swing.ImageIcon(("CavalierJaune.png"))); // NOI18N
        jPanel1.add(jLabel57);

        jLabel58.setIcon(new javax.swing.ImageIcon(("FouJaune.png"))); // NOI18N
        jPanel1.add(jLabel58);

        jLabel59.setIcon(new javax.swing.ImageIcon(("ReineJaune.png"))); // NOI18N
        jPanel1.add(jLabel59);

        jLabel60.setIcon(new javax.swing.ImageIcon(("RoiJaune.png"))); // NOI18N
        jPanel1.add(jLabel60);

        jLabel61.setIcon(new javax.swing.ImageIcon(("FouJaune.png"))); // NOI18N
        jPanel1.add(jLabel61);

        jLabel62.setIcon(new javax.swing.ImageIcon(("CavalierJaune.png"))); // NOI18N
        jPanel1.add(jLabel62);

        jLabel63.setIcon(new javax.swing.ImageIcon(("TourJaune.png"))); // NOI18N
        jPanel1.add(jLabel63);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 30, 520, 520);

        jLabelFond.setIcon(new javax.swing.ImageIcon(("final.jpg"))); // NOI18N
        jLabelFond.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabelFond);
        jLabelFond.setBounds(0, 0, 800, 590);

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Echiquier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Echiquier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Echiquier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Echiquier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Echiquier().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFond;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
}