package projet.interfaces;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

public class InterfaceChoix extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceChoix
     */
    public InterfaceChoix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jCheckBox1.setBorder(null);
        jCheckBox1.setOpaque(false);
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(373, 250, 30, 30);

        jCheckBox2.setOpaque(false);
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(373, 392, 30, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(380, 220, 160, 20);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(380, 360, 160, 20);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2 min", "1 min", "30 s" }));
        jComboBox1.setBorder(null);
        jComboBox1.setOpaque(false);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(500, 480, 160, 20);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Classique", "Chess 960", "D-Chess" }));
        jComboBox2.setBorder(null);
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox2.setOpaque(false);
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(170, 480, 150, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(("lancerpartie.jpg"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.setBorder(BorderFactory.createEmptyBorder());
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 520, 205, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon(("options.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>
  //Evenement entrer sortie de boutton 1 : 
    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {
    	jButton1.setIcon(new ImageIcon("lancerpartieclic.jpg"));
        // TODO add your handling code here:
    }
    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {
    	jButton1.setIcon(new ImageIcon("lancerpartie.jpg"));
        // TODO add your handling code here:
    }
    
    //Evenement clic boutton 1: 
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
    	this.hide();
    	new Echiquier().setVisible(true); 
    	  // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceChoix().setVisible(true);
            }
        });
    }
  
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration
}