package projet.interfaces;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

public class Regles extends javax.swing.JFrame {

    /**
     * Creates new form Regles
     */
    public Regles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        
        setPreferredSize(new java.awt.Dimension(800, 630));
        getContentPane().setLayout(null);
//Spécification boutton quitter : 
        jButton1.setIcon(new javax.swing.ImageIcon("bouton.jpg"));// NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.setBorder(BorderFactory.createEmptyBorder());
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 530, 200, 60);
//spécification label : 
        jLabel2.setIcon(new javax.swing.ImageIcon("principalsansretour.jpg")); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>
    
  //Evenement entrer sortie de boutton 1 : 
    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {
    	jButton1.setIcon(new ImageIcon("boutonclic.jpg"));
        // TODO add your handling code here:
    }
    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {
    	jButton1.setIcon(new ImageIcon("bouton.jpg"));
        // TODO add your handling code here:
    }
  //Evenement clic boutton 1: 
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
    	this.hide();
    	new Accueil().setVisible(true); 
    	  // TODO add your handling code here:
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regles().setVisible(true);
            }
        });
        
      
    }
  
    
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration
}